<?php

namespace common\tests\unit\models;

use common\models\TaskAttachment;
use common\models\Task;
use Codeception\Test\Unit;

class TaskAttachmentTest extends Unit
{
    protected function _before()
    {
        TaskAttachment::deleteAll();
        Task::deleteAll();
    }

    /* =====================================
     * VALIDATION TESTS
     * ===================================== */

    public function testValidationFailsWithoutRequiredFields()
    {
        $model = new TaskAttachment();

        $this->assertFalse($model->validate());
        $this->assertArrayHasKey('task_id', $model->errors);
        $this->assertArrayHasKey('file', $model->errors);
    }

    public function testValidationFailsWithNonIntegerTaskId()
    {
        $model = new TaskAttachment([
            'task_id' => 'abc',
            'file' => 'test.png'
        ]);

        $this->assertFalse($model->validate());
        $this->assertArrayHasKey('task_id', $model->errors);
    }

    public function testValidationFailsWhenFileExceedsMaxLength()
    {
        $model = new TaskAttachment([
            'task_id' => 1,
            'file' => str_repeat('a', 300)
        ]);

        $this->assertFalse($model->validate());
        $this->assertArrayHasKey('file', $model->errors);
    }

    public function testValidationPassesWithValidData()
    {
        $model = new TaskAttachment([
            'task_id' => 1,
            'file' => 'attachment.pdf'
        ]);

        $this->assertTrue($model->validate());
    }

    /* =====================================
     * SAVE & beforeSave TEST
     * ===================================== */

    public function testCreatedAtIsAutoGeneratedOnSave()
    {
        $model = new TaskAttachment([
            'task_id' => 1,
            'file' => 'image.png'
        ]);

        $this->assertTrue($model->save());
        $this->assertNotNull($model->created_at);
        $this->assertIsInt($model->created_at);
    }

    /* =====================================
     * RELATION TEST
     * ===================================== */

    public function testTaskRelation()
    {
        $task = new Task([
            'title' => 'Test Task',
            'status' => 'todo'
        ]);
        $task->save(false);

        $attachment = new TaskAttachment([
            'task_id' => $task->id,
            'file' => 'doc.pdf'
        ]);
        $attachment->save(false);

        $this->assertInstanceOf(Task::class, $attachment->task);
        $this->assertEquals($task->id, $attachment->task->id);
    }
}
